### ISSUE TITLE
为什么源文件是 .txt 格式呢？

### ISSUE THREAD

**Issue by skyleaworlder** [1952560/algorithm#1]
RT

**Comment by 1952560** [comment]
额，感觉txt打开比较快，利于复制粘贴，. cpp打开略慢hh------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Jiageng&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月17日(星期六) 下午4:03
收件人:&nbsp;&quot;1952560/algorithm&quot;<algorithm@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[1952560/algorithm] 为什么源文件是 .txt 格式呢？ (#1)

**Comment by skyleaworlder** [comment]
😄
